# Docker compose files used for testing in container
version: '3'

services:
  service:
    build:
      context: .
      # stop at the dependency stage
      target: base
    # override the command to run the test functions
    command: ['run', 'test:ci']
    entrypoint: npm
    depends_on:
      - mysql
      - redis
    environment:
      SQL_HOST: mysql
      REDIS_HOST: redis
      SQL_PASSWORD: root

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management
    expose:
      - '3306'

  redis:
    image: redis:6-alpine
    expose:
      - '6379'
